// <auto-generated />
using System;
using Kodlama.io.Devs.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kodlama.io.Devs.Persistence.Migrations
{
    [DbContext(typeof(MsSqlQueryDbContext))]
    [Migration("20220904202731_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Kodlama.io.Devs.Domain.Entities.ProgrammingLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstReleaseDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ProgrammingLanguages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("82bf2f0c-3cec-4cdf-9c05-bb6ed13dc34a"),
                            FirstReleaseDate = "08/10/2001",
                            Name = "C#"
                        },
                        new
                        {
                            Id = new Guid("162a541e-61e3-43b7-bef7-cef361be7bc8"),
                            FirstReleaseDate = "23/01/1996",
                            Name = "Java"
                        },
                        new
                        {
                            Id = new Guid("c66d5c35-b336-4296-9394-a21f4ae4ae99"),
                            FirstReleaseDate = "10/11/2009",
                            Name = "Go"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
