// <auto-generated />
using System;
using Kodlama.io.Devs.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kodlama.io.Devs.Persistence.Migrations.MsSqlCommandDb
{
    [DbContext(typeof(MsSqlCommandDbContext))]
    [Migration("20220904203014_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Kodlama.io.Devs.Domain.Entities.ProgrammingLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstReleaseDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ProgrammingLanguages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9fbe5384-8b9b-4b77-ba73-317a1984fc55"),
                            FirstReleaseDate = "08/10/2001",
                            Name = "C#"
                        },
                        new
                        {
                            Id = new Guid("3022cff5-dba4-45cd-be6f-414a97a3655b"),
                            FirstReleaseDate = "23/01/1996",
                            Name = "Java"
                        },
                        new
                        {
                            Id = new Guid("9b223aab-fd15-4277-afb7-86275896549d"),
                            FirstReleaseDate = "10/11/2009",
                            Name = "Go"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
